package data;
// Generated Jun 26, 2017 8:01:15 PM by Hibernate Tools 4.3.1



/**
 * Agenda generated by hbm2java
 */
public class Agenda  implements java.io.Serializable {


     private Integer id;
     private Applied applied;
     private Sessions sessions;
     private Byte liked;
     private String comment;
     private Byte grade;

    public Agenda() {
    }

	
    public Agenda(Applied applied, Sessions sessions) {
        this.applied = applied;
        this.sessions = sessions;
    }
    public Agenda(Applied applied, Sessions sessions, Byte liked, String comment, Byte grade) {
       this.applied = applied;
       this.sessions = sessions;
       this.liked = liked;
       this.comment = comment;
       this.grade = grade;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Applied getApplied() {
        return this.applied;
    }
    
    public void setApplied(Applied applied) {
        this.applied = applied;
    }
    public Sessions getSessions() {
        return this.sessions;
    }
    
    public void setSessions(Sessions sessions) {
        this.sessions = sessions;
    }
    public Byte getLiked() {
        return this.liked;
    }
    
    public void setLiked(Byte liked) {
        this.liked = liked;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Byte getGrade() {
        return this.grade;
    }
    
    public void setGrade(Byte grade) {
        this.grade = grade;
    }




}


