package data;
// Generated Jul 7, 2017 7:28:47 PM by Hibernate Tools 4.3.1



/**
 * Agenda generated by hbm2java
 */
public class Agenda  implements java.io.Serializable {


     private Integer id;
     private Applied applied;
     private Sessions sessions;
     private byte liked;
     private String comment;
     private byte grade;

    public Agenda() {
    }

	
    public Agenda(Applied applied, Sessions sessions, byte liked, byte grade) {
        this.applied = applied;
        this.sessions = sessions;
        this.liked = liked;
        this.grade = grade;
    }
    public Agenda(Applied applied, Sessions sessions, byte liked, String comment, byte grade) {
       this.applied = applied;
       this.sessions = sessions;
       this.liked = liked;
       this.comment = comment;
       this.grade = grade;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Applied getApplied() {
        return this.applied;
    }
    
    public void setApplied(Applied applied) {
        this.applied = applied;
    }
    public Sessions getSessions() {
        return this.sessions;
    }
    
    public void setSessions(Sessions sessions) {
        this.sessions = sessions;
    }
    public byte getLiked() {
        return this.liked;
    }
    
    public void setLiked(byte liked) {
        this.liked = liked;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public byte getGrade() {
        return this.grade;
    }
    
    public void setGrade(byte grade) {
        this.grade = grade;
    }




}


