package data;
// Generated Jul 7, 2017 7:28:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Applied generated by hbm2java
 */
public class Applied  implements java.io.Serializable {


     private Integer id;
     private Conferences conferences;
     private User user;
     private Set agendas = new HashSet(0);

    public Applied() {
    }

	
    public Applied(Conferences conferences, User user) {
        this.conferences = conferences;
        this.user = user;
    }
    public Applied(Conferences conferences, User user, Set agendas) {
       this.conferences = conferences;
       this.user = user;
       this.agendas = agendas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Conferences getConferences() {
        return this.conferences;
    }
    
    public void setConferences(Conferences conferences) {
        this.conferences = conferences;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set agendas) {
        this.agendas = agendas;
    }




}


