package data;
// Generated Jun 26, 2017 8:01:15 PM by Hibernate Tools 4.3.1



/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private Integer id;
     private Lectures lectures;
     private User user;
     private String name;
     private byte isPrezenting;
     private byte[] pdf;
     private byte[] ppt;

    public Author() {
    }

	
    public Author(Lectures lectures, byte isPrezenting) {
        this.lectures = lectures;
        this.isPrezenting = isPrezenting;
    }
    public Author(Lectures lectures, User user, String name, byte isPrezenting, byte[] pdf, byte[] ppt) {
       this.lectures = lectures;
       this.user = user;
       this.name = name;
       this.isPrezenting = isPrezenting;
       this.pdf = pdf;
       this.ppt = ppt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Lectures getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Lectures lectures) {
        this.lectures = lectures;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte getIsPrezenting() {
        return this.isPrezenting;
    }
    
    public void setIsPrezenting(byte isPrezenting) {
        this.isPrezenting = isPrezenting;
    }
    public byte[] getPdf() {
        return this.pdf;
    }
    
    public void setPdf(byte[] pdf) {
        this.pdf = pdf;
    }
    public byte[] getPpt() {
        return this.ppt;
    }
    
    public void setPpt(byte[] ppt) {
        this.ppt = ppt;
    }




}


