package data;
// Generated Jul 7, 2017 7:28:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conferences generated by hbm2java
 */
public class Conferences  implements java.io.Serializable {


     private Integer id;
     private Places places;
     private String name;
     private int field;
     private Date applicationDueDate;
     private Set sessionses = new HashSet(0);
     private Set applieds = new HashSet(0);
     private Set moderators = new HashSet(0);

    public Conferences() {
    }

	
    public Conferences(Places places, String name, int field, Date applicationDueDate) {
        this.places = places;
        this.name = name;
        this.field = field;
        this.applicationDueDate = applicationDueDate;
    }
    public Conferences(Places places, String name, int field, Date applicationDueDate, Set sessionses, Set applieds, Set moderators) {
       this.places = places;
       this.name = name;
       this.field = field;
       this.applicationDueDate = applicationDueDate;
       this.sessionses = sessionses;
       this.applieds = applieds;
       this.moderators = moderators;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Places getPlaces() {
        return this.places;
    }
    
    public void setPlaces(Places places) {
        this.places = places;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getField() {
        return this.field;
    }
    
    public void setField(int field) {
        this.field = field;
    }
    public Date getApplicationDueDate() {
        return this.applicationDueDate;
    }
    
    public void setApplicationDueDate(Date applicationDueDate) {
        this.applicationDueDate = applicationDueDate;
    }
    public Set getSessionses() {
        return this.sessionses;
    }
    
    public void setSessionses(Set sessionses) {
        this.sessionses = sessionses;
    }
    public Set getApplieds() {
        return this.applieds;
    }
    
    public void setApplieds(Set applieds) {
        this.applieds = applieds;
    }
    public Set getModerators() {
        return this.moderators;
    }
    
    public void setModerators(Set moderators) {
        this.moderators = moderators;
    }




}


