package data;
// Generated Jun 26, 2017 8:01:15 PM by Hibernate Tools 4.3.1



/**
 * Favourite generated by hbm2java
 */
public class Favourite  implements java.io.Serializable {


     private Integer id;
     private User userByUser;
     private User userByContact;

    public Favourite() {
    }

    public Favourite(User userByUser, User userByContact) {
       this.userByUser = userByUser;
       this.userByContact = userByContact;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUserByUser() {
        return this.userByUser;
    }
    
    public void setUserByUser(User userByUser) {
        this.userByUser = userByUser;
    }
    public User getUserByContact() {
        return this.userByContact;
    }
    
    public void setUserByContact(User userByContact) {
        this.userByContact = userByContact;
    }




}


