package data;
// Generated Jun 26, 2017 8:01:15 PM by Hibernate Tools 4.3.1



/**
 * Gallery generated by hbm2java
 */
public class Gallery  implements java.io.Serializable {


     private Integer id;
     private Sessions sessions;
     private byte[] picture;

    public Gallery() {
    }

    public Gallery(Sessions sessions, byte[] picture) {
       this.sessions = sessions;
       this.picture = picture;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Sessions getSessions() {
        return this.sessions;
    }
    
    public void setSessions(Sessions sessions) {
        this.sessions = sessions;
    }
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }




}


