package data;
// Generated Jul 7, 2017 7:28:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lectures generated by hbm2java
 */
public class Lectures  implements java.io.Serializable {


     private Integer id;
     private Sessions sessions;
     private String title;
     private Date start;
     private int duration;
     private Set authors = new HashSet(0);

    public Lectures() {
    }

	
    public Lectures(Sessions sessions, String title, Date start, int duration) {
        this.sessions = sessions;
        this.title = title;
        this.start = start;
        this.duration = duration;
    }
    public Lectures(Sessions sessions, String title, Date start, int duration, Set authors) {
       this.sessions = sessions;
       this.title = title;
       this.start = start;
       this.duration = duration;
       this.authors = authors;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Sessions getSessions() {
        return this.sessions;
    }
    
    public void setSessions(Sessions sessions) {
        this.sessions = sessions;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }
    public Set getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Set authors) {
        this.authors = authors;
    }




}


