package data;
// Generated Jun 26, 2017 8:01:15 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private User userBySender;
     private User userByReceiver;
     private String text;

    public Messages() {
    }

    public Messages(User userBySender, User userByReceiver, String text) {
       this.userBySender = userBySender;
       this.userByReceiver = userByReceiver;
       this.text = text;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public User getUserBySender() {
        return this.userBySender;
    }
    
    public void setUserBySender(User userBySender) {
        this.userBySender = userBySender;
    }
    public User getUserByReceiver() {
        return this.userByReceiver;
    }
    
    public void setUserByReceiver(User userByReceiver) {
        this.userByReceiver = userByReceiver;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


