package data;
// Generated Jun 26, 2017 8:01:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Places generated by hbm2java
 */
public class Places  implements java.io.Serializable {


     private Integer id;
     private String state;
     private String city;
     private String address;
     private String name;
     private Set hallses = new HashSet(0);

    public Places() {
    }

	
    public Places(String state, String city, String name) {
        this.state = state;
        this.city = city;
        this.name = name;
    }
    public Places(String state, String city, String address, String name, Set hallses) {
       this.state = state;
       this.city = city;
       this.address = address;
       this.name = name;
       this.hallses = hallses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getHallses() {
        return this.hallses;
    }
    
    public void setHallses(Set hallses) {
        this.hallses = hallses;
    }




}


