package data;
// Generated Jul 7, 2017 7:28:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Sessions generated by hbm2java
 */
public class Sessions  implements java.io.Serializable {


     private Integer id;
     private Conferences conferences;
     private Halls halls;
     private Date date;
     private String name;
     private byte type;
     private Set agendas = new HashSet(0);
     private Set lectureses = new HashSet(0);
     private Set galleries = new HashSet(0);

    public Sessions() {
    }

	
    public Sessions(Conferences conferences, Halls halls, Date date, String name, byte type) {
        this.conferences = conferences;
        this.halls = halls;
        this.date = date;
        this.name = name;
        this.type = type;
    }
    public Sessions(Conferences conferences, Halls halls, Date date, String name, byte type, Set agendas, Set lectureses, Set galleries) {
       this.conferences = conferences;
       this.halls = halls;
       this.date = date;
       this.name = name;
       this.type = type;
       this.agendas = agendas;
       this.lectureses = lectureses;
       this.galleries = galleries;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Conferences getConferences() {
        return this.conferences;
    }
    
    public void setConferences(Conferences conferences) {
        this.conferences = conferences;
    }
    public Halls getHalls() {
        return this.halls;
    }
    
    public void setHalls(Halls halls) {
        this.halls = halls;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }
    public Set getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set agendas) {
        this.agendas = agendas;
    }
    public Set getLectureses() {
        return this.lectureses;
    }
    
    public void setLectureses(Set lectureses) {
        this.lectureses = lectureses;
    }
    public Set getGalleries() {
        return this.galleries;
    }
    
    public void setGalleries(Set galleries) {
        this.galleries = galleries;
    }




}


