package data;
// Generated Jun 26, 2017 8:01:15 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String passwrd;
     private String firstName;
     private String lastName;
     private String email;
     private String institution;
     private String gender;
     private byte[] profilePicture;
     private String TSize;
     private String linkedin;
     private String type;
     private Set messagesesForSender = new HashSet(0);
     private Set authors = new HashSet(0);
     private Set applieds = new HashSet(0);
     private Set messagesesForReceiver = new HashSet(0);
     private Set favouritesForUser = new HashSet(0);
     private Set favouritesForContact = new HashSet(0);

    public User() {
    }

	
    public User(String username, String passwrd, String firstName, String lastName, String email, String institution, String gender, String TSize, String type) {
        this.username = username;
        this.passwrd = passwrd;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.institution = institution;
        this.gender = gender;
        this.TSize = TSize;
        this.type = type;
    }
    public User(String username, String passwrd, String firstName, String lastName, String email, String institution, String gender, byte[] profilePicture, String TSize, String linkedin, String type, Set messagesesForSender, Set authors, Set applieds, Set messagesesForReceiver, Set favouritesForUser, Set favouritesForContact) {
       this.username = username;
       this.passwrd = passwrd;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.institution = institution;
       this.gender = gender;
       this.profilePicture = profilePicture;
       this.TSize = TSize;
       this.linkedin = linkedin;
       this.type = type;
       this.messagesesForSender = messagesesForSender;
       this.authors = authors;
       this.applieds = applieds;
       this.messagesesForReceiver = messagesesForReceiver;
       this.favouritesForUser = favouritesForUser;
       this.favouritesForContact = favouritesForContact;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPasswrd() {
        return this.passwrd;
    }
    
    public void setPasswrd(String passwrd) {
        this.passwrd = passwrd;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public byte[] getProfilePicture() {
        return this.profilePicture;
    }
    
    public void setProfilePicture(byte[] profilePicture) {
        this.profilePicture = profilePicture;
    }
    public String getTSize() {
        return this.TSize;
    }
    
    public void setTSize(String TSize) {
        this.TSize = TSize;
    }
    public String getLinkedin() {
        return this.linkedin;
    }
    
    public void setLinkedin(String linkedin) {
        this.linkedin = linkedin;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getMessagesesForSender() {
        return this.messagesesForSender;
    }
    
    public void setMessagesesForSender(Set messagesesForSender) {
        this.messagesesForSender = messagesesForSender;
    }
    public Set getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Set authors) {
        this.authors = authors;
    }
    public Set getApplieds() {
        return this.applieds;
    }
    
    public void setApplieds(Set applieds) {
        this.applieds = applieds;
    }
    public Set getMessagesesForReceiver() {
        return this.messagesesForReceiver;
    }
    
    public void setMessagesesForReceiver(Set messagesesForReceiver) {
        this.messagesesForReceiver = messagesesForReceiver;
    }
    public Set getFavouritesForUser() {
        return this.favouritesForUser;
    }
    
    public void setFavouritesForUser(Set favouritesForUser) {
        this.favouritesForUser = favouritesForUser;
    }
    public Set getFavouritesForContact() {
        return this.favouritesForContact;
    }
    
    public void setFavouritesForContact(Set favouritesForContact) {
        this.favouritesForContact = favouritesForContact;
    }




}


